### ISSUE TITLE
Adding powercasting for a module built on dnd5e

### ISSUE THREAD

**Issue by BSonPosh** [theripper93/enhancedcombathud-dnd5e#10]
I have a module that is built on dnd5e system and it has the ability to cast "tech" powers. Similar to way Starfinder works. The problem is that "spells" don't show up in the cast spell tab because they are not "prepared"  they are set at powercasting. 

Is there a way to tweak this behavior to support showing "powers" that are not prepared and don't take a spell slot?

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
