### ISSUE TITLE
Off hand weapons not showing in bonus actions

### ISSUE THREAD

**Issue by GMToolbox** [theripper93/enhancedcombathud-dnd5e#2]
After updating to the new version of Argon I no longer see off hand weapons showing up in bonus actions.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
