### ISSUE TITLE
Spells panel does not show for Ranger class

### ISSUE THREAD

**Issue by johncarney** [theripper93/enhancedcombathud-dnd5e#8]
When a Ranger reaches 2nd level they gain the spellcasting feature. Accordingly, I would expect Argon Token HUD to show a spell panel for a Ranger. This does not happen. Obviously selected spells can be added to weapon sets, but this seems rather limited.

A spell panel should appear in the HUD for any character that has the ability to cast spells.

<img width="1758" alt="image" src="https://github.com/theripper93/enhancedcombathud-dnd5e/assets/322950/b551e769-8708-44a6-a7dc-d3036cd22b9c">

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
