### ISSUE TITLE
Spells panel does not show for Ranger

### ISSUE THREAD

**Issue by johncarney** [theripper93/enhancedcombathud-dnd5e#9]
## Module(s)

Module | Version
-|-
Argon - Combat HUD (CORE) | 2.5.10
Argon - Combat HUD (DND5E) |  3.1.2

## Conflicting Module(s)

None.

- [x] I have disabled all other modules

## Foundry and System version

- Foundry 11.315
- Dungeons & Dragons Fifth Edition 3.0.3

## OS, Hosting, Browser (if applicable)

- macOS 14.2.1 (Sonoma)
- MoltenHosting
- Google Chrome 122.0.6261.94

## Short description of bug

When a Ranger reaches 2nd level they gain the spellcasting feature. Accordingly, I would expect Argon Combat HUD (DND5E) to show a spell panel for a Ranger. This does not happen.

A spell panel should appear in the HUD for any character that has the ability to cast spells.

## Simple steps to reproduce the bug

1. Install the "Argon - Combat HUD (CORE)" and "Argon - Combat HUD (DND5E)" modules.
2. Create a game world using the "Dungeons & Dragons Fifth Edition" game system.
3. Enable the "Argon - Combat HUD (CORE)" and "Argon - Combat HUD (DND5E)" modules.
4. Create a new scene.
5. Create a new actor. Set the race to "Human" and background to "Acolyte," selecting basic options when prompted.
6. On the character sheet's "Features" tab, set the class to "Ranger."
7. Advance the character to 2nd level.
8. Locate the Spells list in the SRD compendium and open it up.
9. On the character sheet's "Spells" tab, add a couple of spells from the list. I used "Cure Wounds" and "Hunter's Mark."
10. Place the actor on the scene and select the token.
11. Click the "Argon Combat HUD" on the menu, or on the token's context menu.
12. Check whether these is a spells panel in the HUD.

I have tried this with various character races (Half Elf, Gnome) and the same problem occurs. It also does not matter whether the character is equipped or not, nor whether the character has unspent spell slots or not.

## Screenshots and/or Console Errors

<img width="2048" alt="image" src="https://github.com/theripper93/enhancedcombathud-dnd5e/assets/322950/f793fe88-0ed6-422f-9fa6-2826bebfcc27">

**Comment by theripper93** [comment]
You need to set the spells as prepared or open the actor configuration (argon hud, portrait, hover top right, click gear icon) and force a spell view mode

**Comment by johncarney** [comment]
Thank you 🙏

**Comment by theripper93** [comment]
I guess rangers don't technically need to prepare the spells - i'll fix the default behaviour for rangers

**Comment by johncarney** [comment]
That would be great. I also noticed that of the two spells the character knows, only one appears in the spell panel: _Cure Wounds_. The other is a bonus action spell (_Hunter's Mark_), so maybe it's working as intended? I haven't compared this against other spellcasting classes.

<img width="718" alt="image" src="https://github.com/theripper93/enhancedcombathud-dnd5e/assets/322950/009dfb89-d4ed-4724-9c44-16da0ad7ea4f">

**Comment by theripper93** [comment]
I mean, it’s in the bonus action section, I can see it in the screenshot . For how to please come over to the discord

**Comment by johncarney** [comment]
My bad. Sorry to be such a pain.
